FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

RUN pip install --no-cache-dir \
    transformers==4.40.2 \
    einops==0.8.1 \
    safetensors==0.4.5 \
    pandas==2.2.3 \
    pyarrow==21.0.0

WORKDIR /solution
ENTRYPOINT []
